micronaut:
  application:
    name: micronautHerokuDemo
  server:
    port: ${PORT:8080}
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        generator:
          access-token:
            expiration: 2_592_000
        signatures:
          secret:
            generator:
              secret: '2fvU4pXoPGbiKFEdiAQKnOUEFDPTKSAMP9ClNkOaChcC954jGGwHIEfpqRf6yMhEqG4vYilczceTLc7S02C4JAlnzpLq7sTQdwvO'

datasources:
  default:
    url: jdbc:postgresql://ec2-52-51-3-22.eu-west-1.compute.amazonaws.com:5432/d5rf4v27214i3i
    driverClassName: org.postgresql.Driver
    schema: csruletka
    username: 'ileuvcyjricwtq'
    password: 'b321a8548760bb0bf48afab2c4cc72c683e0d4a24c17aa8e43b7efeccfcd42ab'
    minPoolSize: 1
    maxPoolSize: 2
log4j:
  rootLogger: debug,stdout
netty:
  default:
    allocator:
      max-order: 3
